# This script scans the local network for active devices, retrieves their IP and MAC addresses, performs hostname lookups, and provides insights about the type of device based on its characteristics. It uses a combination of ping sweeps, ARP table analysis, and hostname resolution to classify devices as likely computers, mobile devices, virtual machines, or the router itself.

import ipaddress
import subprocess
import re
import platform
import socket

from concurrent.futures import ThreadPoolExecutor

# This script was generated by ChatGPT: https://chatgpt.com/share/69c1009b-011c-8008-8c19-207d71dcf8cd
# It was then reviewed and edited by Rose Barfield

# -----------------------------------
# SETTINGS
# -----------------------------------
MAX_THREADS = 100

# -----------------------------------
# GET NETWORK INFO
# -----------------------------------
def get_network():
    output = subprocess.check_output("ipconfig", text=True, encoding="utf-8", errors="ignore")

    adapters = output.split("\n\n")

    for adapter in adapters:
        if "IPv4 Address" not in adapter:
            continue

        if "192.168.56." in adapter:
            continue

        ip_match = re.search(r"IPv4 Address.*: (\d+\.\d+\.\d+\.\d+)", adapter)
        mask_match = re.search(r"Subnet Mask.*: (\d+\.\d+\.\d+\.\d+)", adapter)
        gateway_match = re.findall(r"(\d+\.\d+\.\d+\.\d+)", adapter)

        if ip_match and mask_match and "Default Gateway" in adapter:
            ip = ip_match.group(1)
            mask = mask_match.group(1)
            gateway = gateway_match[-1] if gateway_match else None

            network = ipaddress.IPv4Network(f"{ip}/{mask}", strict=False)

            return ip, network, gateway

    raise Exception("No active network adapter found")

# -----------------------------------
# PING
# -----------------------------------
param = "-n" if platform.system().lower() == "windows" else "-c"

def ping(ip):
    try:
        result = subprocess.run(
            ["ping", param, "1", "-w", "50", str(ip)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
        return result.returncode == 0
    except:
        return False

# -----------------------------------
# ARP TABLE
# -----------------------------------
def get_arp_table():
    arp_output = subprocess.check_output("arp -a", text=True)

    arp_dict = {}

    for line in arp_output.splitlines():
        match = re.search(r"(\d+\.\d+\.\d+\.\d+)\s+([a-fA-F0-9\-]{17})", line)
        if match:
            arp_dict[match.group(1)] = match.group(2)

    return arp_dict

# -----------------------------------
# HOSTNAME LOOKUP
# -----------------------------------
def get_hostname(ip):
    try:
        return socket.gethostbyaddr(ip)[0]
    except:
        return "not available"

# -----------------------------------
# MAC ANALYSIS
# -----------------------------------
def is_random_mac(mac):
    try:
        first_byte = int(mac.split("-")[0], 16)
        return (first_byte & 2) != 0  # locally administered bit
    except:
        return False

def classify_device(ip, mac, gateway, local_ip):
    if ip == local_ip:
        return "This Device"

    if ip == gateway:
        return "Router (default gateway)"

    if mac != "Unknown":
        prefix = mac.upper()[0:8]

        # Virtual machines
        if prefix in ["08-00-27", "00-05-69", "00-0C-29", "00-50-56"]:
            return "Virtual Machine"

        # Randomised MAC → likely mobile
        if is_random_mac(mac):
            return "Likely Mobile Device (randomised MAC)"

    return "Likely Computer or IoT Device"

# -----------------------------------
# MAIN
# -----------------------------------
def scan_network():
    local_ip, network, gateway = get_network()

    print(f"\nLocal IP: {local_ip}")
    print(f"Gateway: {gateway}")
    print(f"Scanning network: {network}\n")

    active_hosts = []

    # Ping sweep
    with ThreadPoolExecutor(max_workers=MAX_THREADS) as executor:
        results = list(executor.map(ping, network.hosts()))

    for ip, is_up in zip(network.hosts(), results):
        if is_up:
            active_hosts.append(str(ip))

    print(f"Found {len(active_hosts)} active hosts\n")

    arp_table = get_arp_table()

    print(f"{'IP Address':15} {'MAC Address':20} {'Device Name':20} Insight")
    print("-" * 80)

    for ip in active_hosts:
        mac = arp_table.get(ip, "Unknown")
        hostname = get_hostname(ip)
        insight = classify_device(ip, mac, gateway, local_ip)

        print(f"{ip:15} {mac:20} {hostname:20} {insight}")

# -----------------------------------
# RUN
# -----------------------------------
if __name__ == "__main__":
    scan_network()

